# Generated by Django 4.2.1 on 2023-05-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDeTodosOsEstagiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_operacao', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_banco', models.CharField(max_length=3, unique=True, verbose_name='Número do Banco')),
                ('nome_do_banco', models.CharField(max_length=50, unique=True, verbose_name='Nome do Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=35, verbose_name='Cidade')),
            ],
            options={
                'ordering': ('cidade',),
            },
        ),
        migrations.CreateModel(
            name='ConjAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoounome', models.CharField(max_length=25, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Conj. de Atividades',
            },
        ),
        migrations.CreateModel(
            name='ConjAtividadeEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoounome', models.CharField(max_length=25, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Conj. de Atividades Especificas',
                'verbose_name_plural': 'Conjuntos de Ativ. Espec.',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=35)),
                ('telefone', models.CharField(max_length=20)),
                ('ramal', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Coordenadores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Estados dos Documentos',
            },
        ),
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_estagiario', models.CharField(max_length=70, verbose_name='Nome')),
                ('nome_do_solicitante', models.CharField(blank=True, max_length=50, verbose_name='Nome do Solicitante')),
                ('end_rua', models.CharField(blank=True, max_length=45, verbose_name='Logradouro')),
                ('end_num', models.CharField(blank=True, max_length=15, verbose_name='Núm.')),
                ('end_compl', models.CharField(blank=True, max_length=30, verbose_name='Coml')),
                ('telefones', models.CharField(blank=True, max_length=45, verbose_name='Fones')),
                ('end_bairro', models.CharField(blank=True, max_length=40, verbose_name='Bairro')),
                ('bloco1', models.BooleanField()),
                ('bloco2', models.BooleanField()),
                ('bloco1_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Bloco 1 R$:')),
                ('bloco2_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Bloco 2 R$:')),
                ('data_de_inicio_do_estagio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('data_de_termino_do_estagio', models.DateField(blank=True, null=True, verbose_name='Término')),
                ('data_prevista_para_inicio', models.DateField(blank=True, null=True, verbose_name='Data Prevista para Início')),
                ('data_prevista_para_termino', models.DateField(blank=True, null=True, verbose_name='Data Prevista para Término')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('num_matricula_ufpr', models.CharField(blank=True, max_length=25, null=True)),
                ('data_da_ultima_atualizacao', models.DateField(auto_now=True, null=True)),
                ('data_do_cadastro', models.DateField(auto_now_add=True, null=True)),
                ('numero_no_ciee', models.PositiveIntegerField(blank=True, null=True)),
                ('nome_da_mae', models.CharField(blank=True, max_length=65, null=True)),
                ('data_nasc_mae', models.DateField(blank=True, null=True)),
                ('estudante_da_ufpr', models.BooleanField(blank=True, verbose_name='Estuda na UFPR?')),
                ('teste2', models.TextField(blank=True, null=True)),
                ('teste3', models.IntegerField(blank=True, null=True)),
                ('teste4', models.CharField(blank=True, max_length=2, null=True)),
                ('teste', models.CharField(blank=True, max_length=7, null=True)),
                ('rg', models.CharField(blank=True, max_length=25, null=True)),
                ('cpf', models.CharField(blank=True, max_length=25, null=True)),
                ('conta_corrente', models.CharField(blank=True, max_length=25, null=True)),
                ('agencia', models.CharField(blank=True, max_length=10, null=True)),
                ('falta_pagamento', models.BooleanField(blank=True, verbose_name='Não Recebeu')),
                ('reclamou_pagamento', models.BooleanField(blank=True, verbose_name='Reclamou Pag.')),
                ('obs', models.TextField(blank=True, null=True)),
                ('verificar_pagamento', models.BooleanField(blank=True, verbose_name='Verif. Pag.')),
                ('pagamento_pendente', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('texto1', models.TextField(blank=True, null=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.banco')),
                ('conj_atividades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.conjatividade')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.curso')),
                ('end_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=85)),
            ],
            options={
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='InstituicaoDeEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Instituições de Ensino',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='ItemFotografado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Itens Fotografados',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_local', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='TipoDeContatamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_do_tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Contatamento',
            },
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='TipoDePendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Pendencia',
            },
        ),
        migrations.CreateModel(
            name='SubProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balnres', models.CharField(choices=[('Balneabilidade', 'Balneabilidade'), ('Resíduos', 'Resíduos'), ('QG', 'Administração'), ('ARRUMAR', 'ARRUMAR')], max_length=23, verbose_name='Balneabilidade / Residuos')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.cidade')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_projeto', models.IntegerField(verbose_name='Número do Projeto na Funpar')),
                ('nome_do_projeto', models.CharField(max_length=50, unique=True, verbose_name='Nome do Projeto')),
                ('cc_agencia', models.CharField(max_length=10, verbose_name='Agencia')),
                ('cc_num_conta', models.CharField(max_length=20, verbose_name='Conta Corrente')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_atualizacao', models.DateField(auto_now=True, null=True)),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.estagiario')),
                ('tipo_de_pendencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.tipodependencia')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('item_fotografado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.itemfotografado')),
            ],
        ),
        migrations.AddField(
            model_name='estagiario',
            name='instituicao_de_ensino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.instituicaodeensino'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.projeto'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='subprojeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.subprojeto'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_envio_ou_chegada', models.DateTimeField(blank=True, null=True)),
                ('preenchido', models.BooleanField(blank=True)),
                ('assinado', models.BooleanField(blank=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.estadododocumento')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.estagiario')),
                ('local_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.local')),
                ('tipo_de_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.tipodedocumento')),
            ],
            options={
                'ordering': ('estagiario',),
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('telefone', models.CharField(max_length=45)),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Contatamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_hora', models.DateTimeField()),
                ('ocorrido', models.CharField(blank=True, max_length=100, null=True)),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.estagiario')),
                ('tipo_de_contatamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.tipodecontatamento')),
            ],
        ),
        migrations.CreateModel(
            name='ConjConjAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoounome', models.CharField(max_length=25, verbose_name='Descrição')),
                ('atividadesdafuncao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.conjatividadeespecifica')),
                ('atividadesdoprojeto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.conjatividade')),
            ],
            options={
                'verbose_name': 'Conj. de conj. de atividades',
                'verbose_name_plural': 'Conjuntos de conj. de atividades',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.estado'),
        ),
        migrations.CreateModel(
            name='AvaliacaoDeEstagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_unica', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('assiduidade', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('criatividade', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('iniciativa', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('responsabilidade', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2, verbose_name='Responsab.')),
                ('conduta', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('dominio_do_conhecimento_tecnico', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('dominio_de_habilidades_necessarias_ao_desempenho', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('outros', models.CharField(choices=[('MB', 'Muito Bom'), ('B', 'Bom'), ('R', 'Regular'), ('I', 'Insuficiente')], max_length=2)),
                ('total_de_horas_efetivamente_realizadas', models.FloatField()),
                ('parecer_sobre_o_desempenho_do_estagiario', models.TextField(verbose_name='Com base na avaliação, emita parecer sobre o desempenho do estagiário')),
                ('modalidade_de_supervisao', models.CharField(choices=[('D', 'Direta'), ('S', 'Semi-Direta'), ('I', 'Indireta')], help_text='Definir qual a modalidade de supervisão', max_length=15)),
                ('horas_orientador', models.FloatField()),
                ('horas_supervisor', models.FloatField()),
                ('avaliado', models.BooleanField()),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.estagiario', unique=True)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.avaliacaodetodososestagiarios')),
            ],
            options={
                'verbose_name_plural': 'Avaliações de Estagiários',
            },
        ),
        migrations.CreateModel(
            name='AtividadeEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.TextField()),
                ('conjatividade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.conjatividadeespecifica')),
            ],
            options={
                'verbose_name_plural': 'Atividades Especificas',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.TextField()),
                ('conjatividade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadestagiarios.conjatividade')),
            ],
        ),
    ]
