# Generated by Django 4.2.1 on 2023-05-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadestagiarios', '0002_alter_avaliacaodeestagiario_estagiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='end_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.estado'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='conjatividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.conjatividade'),
        ),
        migrations.AlterField(
            model_name='atividadeespecifica',
            name='conjatividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.conjatividadeespecifica'),
        ),
        migrations.AlterField(
            model_name='avaliacaodeestagiario',
            name='estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.estagiario', unique=True),
        ),
        migrations.AlterField(
            model_name='avaliacaodeestagiario',
            name='operacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.avaliacaodetodososestagiarios'),
        ),
        migrations.AlterField(
            model_name='conjconjatividades',
            name='atividadesdafuncao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.conjatividadeespecifica'),
        ),
        migrations.AlterField(
            model_name='conjconjatividades',
            name='atividadesdoprojeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.conjatividade'),
        ),
        migrations.AlterField(
            model_name='contatamento',
            name='estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.estagiario'),
        ),
        migrations.AlterField(
            model_name='contatamento',
            name='tipo_de_contatamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.tipodecontatamento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.instituicao'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.estadododocumento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.estagiario'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='local_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.local'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_de_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.tipodedocumento'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.banco'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='conj_atividades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.conjatividade'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.curso'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='end_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.cidade'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='instituicao_de_ensino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.instituicaodeensino'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.projeto'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='subprojeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.subprojeto'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='item_fotografado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.itemfotografado'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.estagiario'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='tipo_de_pendencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.tipodependencia'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.banco'),
        ),
        migrations.AlterField(
            model_name='subprojeto',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.cidade'),
        ),
        migrations.AlterField(
            model_name='subprojeto',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadestagiarios.coordenador'),
        ),
    ]
